# Generated by Django 2.1.1 on 2018-10-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_num', models.CharField(max_length=64)),
                ('customer', models.CharField(max_length=64)),
                ('server_type', models.CharField(choices=[(1, 'SDH/MSTP'), (2, 'VSEP'), (3, '高速行情'), (4, '沪港通'), (5, '数据中心'), (6, '自用线路')], max_length=24)),
                ('apply_basis', models.CharField(choices=[(1, 'BMS'), (2, '业务流程单')], max_length=24)),
                ('apply_type', models.CharField(choices=[(1, '新开'), (2, '撤销'), (3, '搬迁'), (4, '升速'), (5, '降速')], max_length=4)),
                ('speed', models.CharField(max_length=10)),
                ('line_type', models.CharField(choices=[(1, 'MSTP'), (2, 'SDH'), (3, '互联网'), (4, '裸光纤')], max_length=8)),
                ('area', models.CharField(choices=[(1, '本地'), (2, '长途')], max_length=4)),
                ('nonrecurring_expense', models.IntegerField()),
                ('monthly_fee', models.FloatField()),
                ('billing_begin', models.DateField()),
                ('billing_end', models.DateField()),
                ('local_address', models.CharField(max_length=128)),
                ('remote_address', models.CharField(max_length=128)),
                ('vlan', models.IntegerField()),
                ('username', models.CharField(max_length=32)),
                ('phone_num', models.CharField(max_length=64)),
                ('apply_date', models.DateField()),
                ('contract_num', models.CharField(max_length=64)),
                ('first_confirm_date', models.DateField()),
                ('apply_seal_date', models.DateField()),
                ('ems_date', models.DateField()),
                ('order_num', models.CharField(max_length=64)),
                ('receive_order_date', models.DateField()),
                ('line_num', models.CharField(max_length=64)),
                ('construct_date', models.DateField()),
                ('complete_date', models.DateField()),
                ('notice_customer', models.CharField(choices=[(1, '是'), (2, '否')], max_length=4)),
                ('isp_report', models.CharField(choices=[(1, '是'), (2, '否')], max_length=4)),
                ('note', models.CharField(max_length=512)),
            ],
        ),
    ]
