# Generated by Django 2.1.1 on 2018-10-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfo',
            name='seal_date',
            field=models.DateField(null=True),
        ),
    ]
